### ISSUE TITLE
maven repo

### ISSUE THREAD

**Issue by perbasilopou** [sparkling-graph/sparkling-graph#18]
maybe there is something wrong with your maven repository. I added the dependencies to my pom.xml, but the imports are wrong at ml.sparkling

**Comment by riomus** [comment]
Are you using snapshot dependencies or release? In order to use snapshot dependencies, you must also add appropriate repository to your pom file.

**Comment by perbasilopou** [comment]
it's version 0.0.7 so i guess it's release?
I copied this:

        <dependency>
            <groupId>ml.sparkling</groupId>
            <artifactId>sparkling-graph_2.11</artifactId>
            <version>0.0.7</version>
        </dependency>

**Comment by riomus** [comment]
Yeas, you are right, the only thing is that there is no sparkling_graph artefact.  [Maven repo](https://mvnrepository.com/artifact/ml.sparkling). There are separate packages for different parts od library.

**Comment by perbasilopou** [comment]
I use intellij, I added the operators and the graph loaders packages from maven.
when i try to import etc this:
import ml.sparkling.graph.operators.OperatorsDSL._
is says the problem is at the "sparkling". 
Do I do something wrong?

**Comment by riomus** [comment]
Try to leave that import and to build your project using Maven, or try to reimport your project using IntelliJ.  With operators and loaders dependencies in your pom, maven should throw an error if there is a problem with dependencies.

**Comment by perbasilopou** [comment]
ok I will try this and tell you if there's something wrong.

**Comment by perbasilopou** [comment]
I got this error:
Error:(12, 11) object sparkling is not a member of package org.apache.spark.ml
import ml.sparkling.graph.operators.OperatorsDSL._

I guess something is wrong with my dependencies, or intellij.
thank you anyway, I close this

**Comment by riomus** [comment]
Here you can find sample scala maven app that use sparkling release version 
https://github.com/sparkling-graph/sparkling-sample-maven

**Comment by perbasilopou** [comment]
I found the mistake, I should have made the imports of your libs on top of the rest imports(like you have them here: http://sparkling-graph.readthedocs.io/en/latest/comunities.html). 
Also you should update this:
`import ml.sparkling.graph.operators.algorithms.pscan. ...`
to:
`import ml.sparkling.graph.operators.algorithms.community.pscan. ...`

**Comment by riomus** [comment]
Awesome to hear that you have solved that. Could you create an issue in documentation repository for that inconsistencies?

**Comment by perbasilopou** [comment]
yes I will. thank you for your help
