### ISSUE TITLE
please implement scan

### ISSUE THREAD

**Issue by niedakh** [sparkling-graph/sparkling-graph#2]
https://gist.github.com/enjoylife/2289625

http://ualr.edu/nxyuruk/publications/kdd07.pdf

**Comment by riomus** [comment]
Implementation will be done basing on paper  ["PSCAN: A Parallel Structural Clustering Algorithm for Big Networks in MapReduce"](http://ieeexplore.ieee.org/xpls/abs_all.jsp?arnumber=6531844&tag=1)

**Comment by riomus** [comment]
After commit 4adc61433f346d3f2eb001e50e58cee17d7b60fc PSCAN is present in SNAPSHOT, please refer to [docs](http://sparkling-graph.readthedocs.org/en/latest/comunities.html#scan-pscan) for more info.

**Comment by niedakh** [comment]
i would like to thank my renowned collegaue @riomus for this work.

**Comment by riomus** [comment]
Present in 0.0.5
