### ISSUE TITLE
eigensystem solver

### ISSUE THREAD

**Issue by fommil** [sparkling-graph/sparkling-graph#6]
hi, just incase you aren't aware of what's available, consider using https://github.com/fommil/netlib-java

**Comment by riomus** [comment]
Hi,

Thanks for info, I am aware of Breeze and other libraries for JVM like ND4J. Currently, we are focusing on providing as much  functionalities as possible, that could be useful for researchers and other users. Our next step will be time and resources consumption optimisation. Do you have any propositions what could be optimised? Current implementations utilise as much  as possible from Pregel/BSP like approach.

**Comment by fommil** [comment]
well you quote eigen system solutions in your blurb, so I presume you mean something ARPACK based like I do in matrix-toolkits-java.

**Comment by riomus** [comment]
Yea, I have to update that README to clarify everything. I presume that you are talking about "Eigenvector". What I meant there, is eigenvector centrality for vertices of given graph. It is a vertex measure that is more general that PageRank. Currently, we are using Pregel/BSP implementation for that, but as you probably know, it can also be computed using adjacent matrix for given graph.
