### ISSUE TITLE
Issue with Eigenvector Centrality?!

### ISSUE THREAD

**Issue by blacknred0** [sparkling-graph/sparkling-graph#9]
hi -
I have a question or issue with Eigenvector Centrality.  I have a graph that I am able to create the results by using this calculation, but when I create a subgraph (or even manually importing as a new graph) the calculation seems to take longer and doesn't seem ever to finish.

The only thing that I've noticed is that before subgraphing, Freeman's centrality is <1 and when I do the subgraph Freeman's centrality is >1.

Not sure if you anybody has any pointers.

``` scala
val eic = graph.eigenvectorCentrality().vertices
val evusers = users.join(eic).map {
  case (id, (username, eic)) => (username, eic)
}
```

Thanks in advance!

**Comment by riomus** [comment]
Hi,

Could you provident some exact data example or repo with code for problem reproduction?

**Comment by riomus** [comment]
You could also check  if decreasing [continue predicate](https://github.com/sparkling-graph/sparkling-graph/blob/master/operators/src/main/scala/ml/sparkling/graph/operators/measures/vertex/eigenvector/EigenvectorCentrality.scala#L26). I see that it is not mentioned in documentation, it should be fixed

**Comment by blacknred0** [comment]
Thanks for the quick response.  While I narrow down the code and increase convergence predicate, is there a max convergence predicate number that I should not go over?  I see that right now is at `1e-6`, what if I do `1e-9` or `1e-12` or should I go higher than that.

**Comment by riomus** [comment]
It depends on your use case. Lower the convergence predicate is (remember that 1e-6 > 1e-12) than longer the computation will take but also results are more exact. Try to setting it to 1e-3, or you can try to limit the number of iterations using  [number of iterations](https://github.com/sparkling-graph/sparkling-graph/blob/master/operators/src/main/scala/ml/sparkling/graph/operators/measures/vertex/eigenvector/EigenvectorUtils.scala) that is passed to the predicate. For some specific graphs, centrality can start to oscillate between two values in consecutive iterations, in order to solve that, you can try to limit number of iterations (that is probably your case)

**Comment by blacknred0** [comment]
Thanks for the pointers... so, here is the scoop.  I think the problem is that I am running out of RAM and I have allocated 10G on two executors and one driver.  Usually stops at 2.6K completed RDDs.  Which I think should have been enough RAM for this relative small data set (see below for details).

Here is the core code that I am using.
``` scala
import org.apache.spark.graphx.GraphLoader
import org.apache.spark.sql.SparkSession
import org.apache.spark.SparkContext
import org.apache.spark.graphx.Graph
// Sparkling Graph functions
import ml.sparkling.graph.operators.OperatorsDSL._

val graph = GraphLoader.edgeListFile(sc, "followers.txt").cache()
val eic = graph.eigenvectorCentrality().vertices
```

Here is the dataset for your test.  Note that it is a relative small file with 2.4MB (214,366 rows).
[Followers.txt dataset for test](https://gist.github.com/blacknred0/6af6e183d2e422ca69f967aa639c74c1).

I'm new to scala, so any pointers as of what to change would be helpful!

thanks for your help in advance!

**Comment by riomus** [comment]
You can try to repartition your graph using bigger number of partitions than default (that the first thing that I would do). I will try to look at that issue

**Comment by blacknred0** [comment]
Thanks for the suggestion and try to take a look at this issue... I will give it a try! :)

**Comment by blacknred0** [comment]
I think I have narrowed it down.  The problem is the spark driver.  I actually up it to 15G and it was not enough to process the graph.  I kept track of the utilization (through top) and saw when it was running out of memory.

This happens even after enhancing storing the `edgeListFile` to store all on disk (both edges and vertex).  Which by the way, fixes the problem from above, but not the processing of the spark driver.
``` scala
val graph = GraphLoader.edgeListFile(sc, "followers.txt", 
  vertexStorageLevel = StorageLevel.DISK_ONLY, 
  edgeStorageLevel = StorageLevel.DISK_ONLY)
```

What you point me to what I would need to change on the function to decrease the loop?  Maybe that will help.

Thanks in advance.

**Comment by riomus** [comment]
You can pass your own implementation to continuePredicate, it must be just a function with appropriate [signature](https://github.com/sparkling-graph/sparkling-graph/blob/master/operators/src/main/scala/ml/sparkling/graph/operators/measures/vertex/eigenvector/EigenvectorUtils.scala) 

I think that you should pass something like:
```scala
import org.apache.spark.graphx.GraphLoader
import org.apache.spark.sql.SparkSession
import org.apache.spark.SparkContext
import org.apache.spark.graphx.Graph
import ml.sparkling.graph.operators.measures.vertex.eigenvector.EigenvectorCentrality
import ml.sparkling.graph.operators.OperatorsDSL._

val graph = GraphLoader.edgeListFile(sc, "followers.txt").cache()
val eic = EigenvectorCentrality.computeEigenvector(graph,VertexMeasureConfiguration(),(iteration,_,_)=>iteration<999).vertices
```

Just replace the 999 with appropriate value

**Comment by blacknred0** [comment]
ok, thanks mate! I can confirm that after using `VertexMeasureConfiguration()` and passing the iteration value it works like a charm :)
